### PR TITLE
Version 0.4.0 proposal

### PR DESCRIPTION
**Pull request by eclipxe13**
See `docs/CHANGELOG.md` and `docs/UPGRADE_0.3_0.4.md`

### CODE REVIEW

**Comment by eclipxe13** [comment]
This release solves #18

**Review by blacktrue — APPROVED** [review]
Good job

**Comment by eclipxe13** [comment]
With commit https://github.com/phpcfdi/sat-ws-descarga-masiva/pull/31/commits/87662ca826c2f9b7d991676778343808a1c39707 fix #30

**Comment by eclipxe13** [comment]
The commit https://github.com/phpcfdi/sat-ws-descarga-masiva/pull/31/commits/6b3b67b5a6351c52f9f05532ec3fbb01d9def3a1 fixes #29

**Pull request merged**
